apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxdeployment
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80